name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        
        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '8.0.x'
            source-url: https://nuget.pkg.github.com/kickoffworks/index.json
          env:
            NUGET_AUTH_TOKEN: ${{secrets.NUGET_GITHUB_TOKEN}}
        
        - run: dotnet build Sample.Core/
        
        - name: Create the Infrastructure package
          run: dotnet pack --configuration Release Sample.Core/Sample.Core.Infrastructure
          
        - name: Publish the Infrastructure package to GPR
          env:
            NUGET_AUTH_TOKEN: ${{secrets.NUGET_GITHUB_TOKEN}}
          run: dotnet nuget push Sample.Core/Sample.Core.Infrastructure/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN
          
        - name: Create the Domain package
          run: dotnet pack --configuration Release Sample.Core/Sample.Core.Domain
          
        - name: Publish the Domain package to GPR
          env:
            NUGET_AUTH_TOKEN: ${{secrets.NUGET_GITHUB_TOKEN}}
          run: dotnet nuget push Sample.Core/Sample.Core.Domain/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN
